## **NumPy Arrays and Basics**
Resource: Chai aur Code | *Hitesh Chaudhary*

In [2]:
import numpy as np

#### **Creating NumPy Arrays - 1D and 2D**
> Try keeping similar datatypes as it keeps code optimized.

In [3]:
arr_1D = np.array([1,2,3,4])
print(f"1D array: {arr_1D}")

arr_2D = np.array([[1,2,3,4], [5,6,7,8]])
print(f"\n2D array: \n{arr_2D}")

1D array: [1 2 3 4]

2D array: 
[[1 2 3 4]
 [5 6 7 8]]


#### **Python Lists vs NumPy Arrays**
- List multiplications duplicates n number of times.
- Array multiplications multiplies elements with n.

##### ***Differences***

| Feature                     | Python List (`list`)             | NumPy Array (`np.array`)                 |
|-----------------------------|----------------------------------|------------------------------------------|
| **Data Type Support**       | Can hold mixed types             | Must be same type (e.g., all `int`, `float`) |
| **Performance**             | Slower                          | Much faster (C-optimized)                |
| **Memory Usage**            | More memory                     | Less memory (compact, contiguous)        |
| **Vectorized Operations**   | Not supported (need loops)     | Supports element-wise ops (`+`, `*`, etc.) |
| **Multidimensional Support**| Manual (lists of lists)         | Built-in (e.g., 2D, 3D arrays)           |
| **Built-in Functions**      | Fewer (basic list methods)      | Many (e.g., `np.mean`, `np.sum`, etc.)   |
| **Indexing/Slicing**        | Basic slicing                   | Advanced (boolean, fancy indexing)       |
| **Broadcasting**            | Not supported                 | Automatic shape matching for ops      |


In [4]:
py_list = [1,2,3,4]
print(f"Python list multiplication: {py_list*2}")

np_array = np.array([1,2,3,4])
print(f"Python array multiplication: {np_array*2}")

# Checking time of execution in list vs array:
import time

start = time.time()
py_list = [i*2 for i in range (10000000)]
print(f"\nTime taken by list: {time.time() - start}")

start = time.time()
np_array = np.arange(10000000)*2
print(f"Time taken by array: {time.time() - start}")

Python list multiplication: [1, 2, 3, 4, 1, 2, 3, 4]
Python array multiplication: [2 4 6 8]

Time taken by list: 0.666440486907959
Time taken by array: 0.05787372589111328


#### **Types of arrays**
- **Zeros and Ones Array**:
    - Zeros: ```np.zeros((row_dimension, col_dimension))```
    - Ones: ```np.ones((row_dimension, col_dimension))```

In [5]:
zeros = np.zeros((3,6))
print(f"Zeros array: \n{zeros}")

ones = np.ones((3,3))
print(f"\nOnes array: \n{ones}")

Zeros array: 
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

Ones array: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


- **Full Array**:
    - Full: ```np.full((row_dimension, col_dimension), constant)```

In [6]:
full = np.full((2,3), 7)
print(f"Full array: \n{full}")

Full array: 
[[7 7 7]
 [7 7 7]]


- **Random Value Arrays**:
    - This uses methods from random class, and generates numbers between ```0``` and ```1```.
    - Random array: ```np.random.random((row_dimension, col_dimension))```

In [7]:
random = np.random.random((4,4))
print(f"Random value array: \n{random}")

Random value array: 
[[0.06735728 0.532101   0.54536686 0.8785809 ]
 [0.45692845 0.28741234 0.92483429 0.51263007]
 [0.98109818 0.57539737 0.13078478 0.41589456]
 [0.26898781 0.12442973 0.73999429 0.48015942]]


- **Sequence Array**:
    - Sequence: ```np.arange(start, end, steps)```

In [8]:
sequence = np.arange(2, 20, 2)
print(f"Sequence array: {sequence}")

Sequence array: [ 2  4  6  8 10 12 14 16 18]


#### **Vector, Matrix and Tensor**
- **Vector**: A 1D NumPy array (e.g., `[1, 2, 3]`) representing a list of values.
- **Matrix**: A 2D NumPy array with rows and columns (e.g., `[[1, 2], [3, 4]]`).
- **Tensor**: A general n-dimensional NumPy array (e.g., 3D: `[[[1], [2]], [[3], [4]]]`).


In [9]:
vector = np.array([1,2,3])
print(f"Vector: \n{vector}")

matrix = np.array([[1,2,3],
                   [4,5,6]])
print(f"\nMatrix: \n{matrix}")

tensor = np.array([[[1,2,3], [4,5,6]],
                   [[7,8,9], [10,11,12]],
                   [[13,14,15], [15,16,17]]])
print(f"\nTensor: \n{tensor}")

Vector: 
[1 2 3]

Matrix: 
[[1 2 3]
 [4 5 6]]

Tensor: 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [15 16 17]]]


#### **Array Properties**
- **Shape**: 
    - ```shape```: Returns a tuple representing the number of elements along each dimension (e.g., `(3, 2)` for 3 rows and 2 columns).
- **Dimensions** 
    - ```ndim```: Returns the number of dimensions (axes) of the array.
- **Size** 
    - ```size```: Returns the total number of elements in the array.
- **Data Type** 
    - ```dtype```: Returns the data type of elements stored in the array (e.g., `int32`, `float64`).

In [11]:
tensor = np.array([[[1,2,3], [4,5,6]],
                   [[7,8,9], [10,11,12]],
                   [[13,14,15], [15,16,17]]])

print(f"Tensor shape: {tensor.shape}")
print(f"Tensor dimension: {tensor.ndim}")
print(f"Tensor size: {tensor.size}")
print(f"Tensor datatype: {tensor.dtype}")

Tensor shape: (3, 2, 3)
Tensor dimension: 3
Tensor size: 18
Tensor datatype: int64


#### **Array Reshaping & Flattening**
- **Reshaping** means changing the shape of an existing array without changing its data.
    - Use `np.reshape(array, new_shape)` to convert the array into a new shape (rows × columns).

- **Flattening** means converting a multi-dimensional array into a 1D array.
    - Use `.flatten()` or `.ravel()` to do this.
    - `.flatten()` returns copy, instead of view.
    - `.ravel()` returns view, instead of copy.
- **Transpose** means flipping the array over its diagonal — converting rows to columns and vice versa.
    - Use `.T` or `np.transpose(array)` to perform the transpose.

In [16]:
arr = np.arange(12)
print(f"Original array: {arr}")

reshaped_arr = arr.reshape(4,3)
print(f"\nReshaped array: \n{reshaped_arr}")

flattened_arr = reshaped_arr.flatten()
print(f"\nFlattened array: {flattened_arr}")

raveled_arr = reshaped_arr.ravel()
print(f"\nRavelled array: {raveled_arr}")

transposed_arr = reshaped_arr.T
print(f"\nTransposed array: \n{transposed_arr}")

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array: 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Ravelled array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Transposed array: 
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
