## **NumPy Arrays and Basics**
Resource: Chai aur Code | ***Hitesh Chaudhary***

In [1]:
import numpy as np

#### **Creating NumPy Arrays - 1D and 2D**
> Try keeping similar datatypes as it keeps code optimized.

In [12]:
arr_1D = np.array([1,2,3,4])
print(f"1D array: {arr_1D}")

arr_2D = np.array([[1,2,3,4], [5,6,7,8]])
print(f"\n2D array: \n{arr_2D}")

1D array: [1 2 3 4]

2D array: 
[[1 2 3 4]
 [5 6 7 8]]


#### **Python Lists vs NumPy Arrays**
- List multiplications duplicates n number of times.
- Array multiplications multiplies elements with n.

##### ***Differences***

| Feature                     | Python List (`list`)             | NumPy Array (`np.array`)                 |
|-----------------------------|----------------------------------|------------------------------------------|
| **Data Type Support**       | Can hold mixed types             | Must be same type (e.g., all `int`, `float`) |
| **Performance**             | Slower                          | Much faster (C-optimized)                |
| **Memory Usage**            | More memory                     | Less memory (compact, contiguous)        |
| **Vectorized Operations**   | Not supported (need loops)     | Supports element-wise ops (`+`, `*`, etc.) |
| **Multidimensional Support**| Manual (lists of lists)         | Built-in (e.g., 2D, 3D arrays)           |
| **Built-in Functions**      | Fewer (basic list methods)      | Many (e.g., `np.mean`, `np.sum`, etc.)   |
| **Indexing/Slicing**        | Basic slicing                   | Advanced (boolean, fancy indexing)       |
| **Broadcasting**            | Not supported                 | Automatic shape matching for ops      |


In [7]:
py_list = [1,2,3,4]
print(f"Python list multiplication: {py_list*2}")

np_array = np.array([1,2,3,4])
print(f"Python array multiplication: {np_array*2}")

# Checking time of execution in list vs array:
import time

start = time.time()
py_list = [i*2 for i in range (10000000)]
print(f"\nTime taken by list: {time.time() - start}")

start = time.time()
np_array = np.arange(10000000)*2
print(f"Time taken by array: {time.time() - start}")

Python list multiplication: [1, 2, 3, 4, 1, 2, 3, 4]
Python array multiplication: [2 4 6 8]

Time taken by list: 1.1423993110656738
Time taken by array: 0.06411170959472656


#### **Types of arrays**
- **Zeros and Ones Array**:
    - Zeros: ```np.zeros((row_dimension, col_dimension))```
    - Ones: ```np.ones((row_dimension, col_dimension))```

In [11]:
zeros = np.zeros((3,6))
print(f"Zeros array: \n{zeros}")

ones = np.ones((3,3))
print(f"\nOnes array: \n{ones}")

Zeros array: 
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

Ones array: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


- **Full Array**:
    - Full: ```np.full((row_dimension, col_dimension), constant)```

In [13]:
full = np.full((2,3), 7)
print(f"Full array: \n{full}")

Full array: 
[[7 7 7]
 [7 7 7]]


- **Random Value Arrays**:
    - This uses methods from random class, and generates numbers between ```0``` and ```1```.
    - Random array: ```np.random.random((row_dimension, col_dimension))```

In [14]:
random = np.random.random((4,4))
print(f"Random value array: \n{random}")

Random value array: 
[[0.42234893 0.39009881 0.24002263 0.53542066]
 [0.67061561 0.9388172  0.56781543 0.00455007]
 [0.19124736 0.75064606 0.81033056 0.45288485]
 [0.21338331 0.70570793 0.99119702 0.49741375]]


- **Sequence Array**:
    - Sequence: ```np.arange(start, end, steps)```

In [15]:
sequence = np.arange(2, 20, 2)
print(f"Sequence array: {sequence}")

Sequence array: [ 2  4  6  8 10 12 14 16 18]


#### **Vector, Matrix and Tensor**
- **Vector**: A 1D NumPy array (e.g., `[1, 2, 3]`) representing a list of values.
- **Matrix**: A 2D NumPy array with rows and columns (e.g., `[[1, 2], [3, 4]]`).
- **Tensor**: A general n-dimensional NumPy array (e.g., 3D: `[[[1], [2]], [[3], [4]]]`).


In [19]:
vector = np.array([1,2,3])
print(f"Vector: \n{vector}")

matrix = np.array([[1,2,3],
                   [4,5,6]])
print(f"\nMatrix: \n{matrix}")

tensor = np.array([[[1,2,3], [4,5,6]],
                   [[7,8,9], [10,11,12]],
                   [[13,14,15], [15,16,17]]])
print(f"\nTensor: \n{tensor}")

Vector: 
[1 2 3]

Matrix: 
[[1 2 3]
 [4 5 6]]

Tensor: 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [15 16 17]]]
