## **NumPy Array Operations**


In [2]:
import numpy as np

#### **Array Slicing - 1D and 2D**
- `:` means select all.
- `start:stop:step` controls the slicing direction and stride.
- Negative steps `(-1)` are used for reversing.

a. **1D Array**

In [4]:
arr_1D = np.array([10,20,30,40,50,60,70,80,90,100])

# slicing:
sliced_arr = arr_1D[2:8]
print(f"Sliced array: {sliced_arr}")

# step slicing
step_sliced_arr = arr_1D[0:9:2]
print(f"Step sliced array: {step_sliced_arr}")

# reverse indexing
print(f"Reversely indexed: {arr_1D[-4]}")

Sliced array: [30 40 50 60 70 80]
Step sliced array: [10 30 50 70 90]
Reversely indexed: 70


b. **2D Array**

In [9]:
arr_2D = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

# basic positioning:
print(f"Element on the position: {arr_2D[2,1]}")

# access entire row:
print(f"Elements in row requested: {arr_2D[1]}")

# access entire column:
print(f"Elements in column requested: {arr_2D[:,0]}")

Element on the position: 8
Elements in row requested: [4 5 6]
Elements in column requested: [1 4 7]


#### **Array Sorting**
NumPy provides powerful functions to sort arrays using `np.sort()` or `.sort()` method.
- `np.sort()` returns a sorted copy.
- `arr.sort()` sorts in-place.

2D Array:
- `np.sort(array, axis=0/1)`
    - `axis=0`: Sorts column-wise
    - `axis=1`: Sorts row-wise

In [12]:
unsorted_arr_1D = np.array([3,1,2,5,6,3,9,0,7,1,8,4])
print(f"Unsorted 1D array: {unsorted_arr_1D}")

sorted_arr_1D = np.sort(unsorted_arr_1D)
print(f"Sorted 1D array: {sorted_arr_1D}")

unsorted_arr_2D = np.array([[1,3],
                            [2,1],
                            [2,3]])
print(f"\n2D array sorted column-wise: \n{np.sort(unsorted_arr_2D, axis=0)}")
print(f"2D array sorted row-wise: \n{np.sort(unsorted_arr_2D, axis=1)}")

Unsorted 1D array: [3 1 2 5 6 3 9 0 7 1 8 4]
Sorted 1D array: [0 1 1 2 3 3 4 5 6 7 8 9]

2D array sorted column-wise: 
[[1 1]
 [2 3]
 [2 3]]
2D array sorted row-wise: 
[[1 3]
 [1 2]
 [2 3]]


#### **Filtering**
- **Filtering** allows you to extract elements that meet a condition.
- You create a **boolean mask** using comparison operators, and apply it to the array.
- Conditions can be combined using `&` (and), `|` (or), `~`(not)
> Always wrap conditions in parentheses when combining them.
1. **One-liner:**

In [13]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
odd_numbers = numbers[numbers % 2 != 0]

print(f"Odd numbers: {odd_numbers}")

Odd numbers: [1 3 5 7 9]


2. **Filtering with Mask:**

In [14]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
mask = numbers > 5

print(f"Numbers greater than 5: {numbers[mask]}")

Numbers greater than 5: [ 6  7  8  9 10]


3. **Combining conditions:**

In [15]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
mask = (numbers > 2) & (numbers < 9) & (numbers % 2 == 0)

print(f"Even numbers between 2 and 9: {numbers[mask]}")

Even numbers between 2 and 9: [4 6 8]


#### **Fancy Indexing & np.where()**
- Fancy indexing lets you access multiple specific indices at once using a list or array of indices.
    - It creates a copy, not a view.
-  np.where() is used for Conditional Element Selection
    - `np.where(condition)` returns the indices where condition is `True`.
    - `np.where(condition, x, y)` returns `x` if condition is `True`, else `y`.
    - `np.where()` is great for quick element-wise conditional logic without loops.


In [19]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])

fancy_indices = [2,4,7]
print(f"Extracted using fancy indexing: {numbers[fancy_indices]}")

only_where = np.where((numbers > 3) & (numbers < 8))
print(f"Extracted using only where: {numbers[only_where]}")

conditional_where = np.where(numbers % 2 != 0, 'o', 'e')
print(f"Extracted using conditional where: {conditional_where}")

Extracted using fancy indexing: [3 5 8]
Extracted using only where: [4 5 6 7]
Extracted using conditional where: ['o' 'e' 'o' 'e' 'o' 'e' 'o' 'e' 'o' 'e']


#### **Adding and Removing**
1. **Concatenation:**

In [ ]:
arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])

combined_arr = np.concatenate((arr_1, arr_2))
print(f"Combined array is: {combined_arr}")

Combined array is: [1 2 3 4 5 6]


3. **Checking compatibility:**

In [ ]:
arr_1 = np.array([[1,2,3,4],
                  [0,1,6,7]])
arr_2 = np.array([[1,2,3],
                  [0,1,6]])
print(f"Both of these arrays are compatible: {arr_2.shape == arr_1.shapeb}")

Both of these arrays are compatible: False


4. **Adding rows (vertical stacking) or columns (horizontal stacking):**
- `np.array` syntax: you need a single iterable of rows, not two separate arguments.
- Row length mismatch: your `new_row` must have the same number of columns as `og_arr`.

In [30]:
og_arr = np.array([[2,3,5],
                  [5,8,9]])
new_row = np.array([29,10,15])

with_new_row = np.vstack((og_arr, new_row))
print(f"Stacking a new row: \n{with_new_row}")

new_col = np.array([[2],
                    [9]])
with_new_col = np.hstack((og_arr, new_col))
print(f"\nStacking a new column: \n{with_new_col}")

Stacking a new row: 
[[ 2  3  5]
 [ 5  8  9]
 [29 10 15]]

Stacking a new column: 
[[2 3 5 2]
 [5 8 9 9]]


5. **Deleting**
- NumPy uses the `np.delete()` function to remove elements from arrays.
- It **returns a new array** (original remains unchanged).
- Works on both 1D and 2D arrays.
- `np.delete(array, obj, axis=None)`
    - `array`: The input array
    - `obj`: Index (or list of indices) to delete
    - `axis`:
        - `None` (default): flattens the array before deletion
        - `0`: delete row(s)
        - `1`: delete column(s)

In [38]:
arr_1 = np.array([1,2,3,4,5,6,7,8,9,10])
arr_2 = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

deleted_arr = np.delete(arr_1,(2,3,7))
print(f"Array after deletion: {deleted_arr}")

deleted_row = np.delete(arr_2, 2, axis=0)
print(f"\nArray after row deletion: \n{deleted_row}")

deleted_col = np.delete(arr_2, 2, axis=1)
print(f"\nArray after col deletion: \n{deleted_col}")

flatten_deleted_arr = np.delete(arr_2, (2,4,7), axis=None)
print(f"\nFlatten array after deletion: {flatten_deleted_arr}")

Array after deletion: [ 1  2  5  6  7  9 10]

Array after row deletion: 
[[1 2 3]
 [4 5 6]]

Array after col deletion: 
[[1 2]
 [4 5]
 [7 8]]

Flatten array after deletion: [1 2 4 6 7 9]
